<?php
/**
 * TL_ROOT/system/modules/tags_events/languages/de/modules.php 
 * 
 * TYPOlight extension: tags_events 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloudevents']['0'] = "Tag Cloud (Events)";
$GLOBALS['TL_LANG']['FMD']['tagcloudevents']['1'] = "Dieses Modul zeigt eine Tag Cloud für Kalendereinträge an.";
 
?>
