<?php
/**
 * TL_ROOT/system/modules/tags_events/languages/de/tl_module.php 
 * 
 * TYPOlight extension: tags_events 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_calendars']['0'] = "Kalender";
$GLOBALS['TL_LANG']['tl_module']['tag_calendars']['1'] = "Bitte wählen Sie die Kalender aus, die für die Anzeige der Tag Cloud verwendet werden sollen.";
 
?>
